function userOptions = defineUserOptions_RL_RN_MF_MB()
%
%  projectOptions is a nullary function which initialises a struct
%  containing the preferences and details for a particular project.
%  It should be edited to taste before a project is run, and a new
%  one created for each substantially different project (though the
%  options struct will be saved each time the project is run under
%  a new name, so all will not be lost if you don't do this).
%
%  For a guide to how to fill out the fields in this file, consult
%  the documentation folder (particularly the userOptions_guide.m)
%
%  Cai Wingfield 11-2009
%__________________________________________________________________________
% Copyright (C) 2009 Medical Research Council

%% Project details

% This name identifies a collection of files which all belong to the same run of a project.
userOptions.analysisName = 'RL_GoNoGo';

% This is the root directory of the project.
%userOptions.rootPath = 'D:\Bochum\DATA\RSA_test\RSA_results';

% The path leading to where the scans are stored (not including subject-specific identifiers).
% "[[subjectName]]" should be used as a placeholder to denote an entry in userOptions.subjectNames
% "[[betaIdentifier]]" should be used as a placeholder to denote an output of betaCorrespondence.m if SPM is not being used; or an arbitrary filename if SPM is being used.
%userOptions.betaPath = ['D:\Bochum\DATA\fMRI_RL_GoNoGo\Results_MD\Participants\','[[subjectName]]',filesep,'Results_outcome_RN_RSA_new',filesep,'[[betaIdentifier]]'];% e.g. /imaging/mb01/lexpro/multivariate/ffx_simple/[[subjectName]]/[[betaIdentifier]]
userOptions.betaPath = ['/Users/binwang/Documents/Bochum/DATA/fMRI_RL_GoNoGo/Results_MD/Participants/','[[subjectName]]',filesep,'Results_outcome_RN_RSA_new_MF_MB',filesep,'[[betaIdentifier]]'];% e.g. /imaging/mb01/lexpro/multivariate/ffx_simple/[[subjectName]]/[[betaIdentifier]]
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% FEATUERS OF INTEREST SELECTION OPTIONS %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

	%% %% %% %% %%
	%% fMRI  %% Use these next three options if you're working in fMRI native space:
	%% %% %% %% %%
	
	% The path to a stereotypical mask data file is stored (not including subject-specific identifiers).
	% "[[subjectName]]" should be used as a placeholder to denote an entry in userOptions.subjectNames
	% "[[maskName]]" should be used as a placeholder to denote an entry in userOptions.maskNames
	userOptions.maskPath = ['/Users/binwang/Documents/Bochum/DATA/fMRI_RL_GoNoGo/Results_MD/Results_RSA/Mask/Mask_MF_MB/[[maskName]].nii'];%'/imaging/mb01/lexpro/multivariate/ffx_simple/[[subjectName]]/[[maskName]].img';
		
		% The list of mask filenames (minus .hdr extension) to be used.
		userOptions.maskNames = { ...
			'dmPFC',...
            'rdlPFC',...
            'rOFC',...
			};

%%%%%%%%%%%%%%%%%%%%%%%%%
%% SEARCHLIGHT OPTIONS %%
%%%%%%%%%%%%%%%%%%%%%%%%%

	%% %% %% %% %%
	%% fMRI  %% Use these next three options if you're working in fMRI native space:
	%% %% %% %% %%

		% What is the path to the anatomical (structural) fMRI scans for each subject?
		% "[[subjectName]]" should be used to denote an entry in userOptions.subjectNames
%		userOptions.structuralsPath = ['D:\Bochum\DATA\RSA_test\','[[subjectName]]',filesep,'T1\'];% e.g. /imaging/mb01/lexpro/[[subjectName]]/structurals/
	
		% What are the dimensions (in mm) of the voxels in the scans?
		userOptions.voxelSize = [2 2 3];
	
		% What radius of searchlight should be used (mm)?
		userOptions.searchlightRadius = 9; % 3 voxels
	
%%%%%%%%%%%%%%%%%%%%%%%%
%% EXPERIMENTAL SETUP %%
%%%%%%%%%%%%%%%%%%%%%%%%

% The list of subjects to be included in the study.
userOptions.subjectNames = { ...
	'Sub02',...
    'Sub03',...
    'Sub04',...
    'Sub05',...
    'Sub07',...
    'Sub08',...
    'Sub11',...
    'Sub13',...
    'Sub14',...
    'Sub15',...    
    'Sub16',...
    'Sub17',...
    'Sub18',...
    'Sub19',...
    'Sub20',...
    'Sub22',...
    'Sub23',...
    'Sub26',...
    'Sub27',...
    'Sub28',...
    'Sub29',...
    'Sub31',...    
    'Sub32',...
    'Sub33',...
    'Sub34',...
    'Sub35',...
    'Sub36',...
    'Sub37',...
    'Sub38',...    
    'Sub39',...
    'Sub40',...
	};% eg CBUXXXXX

% userOptions.subjectNames = { ...
% 	'Sub01',...
%     'Sub02',...
%     'Sub03',...
%     'Sub04',...
%     'Sub05',...
%     'Sub06',...
%     'Sub07',...
%     'Sub08',...
%     'Sub09',...
%     'Sub10',...
%     'Sub11',...
%     'Sub12',...
% 	};% eg CBUXXXXX
% The default colour label for RDMs corresponding to RoI masks (as opposed to models).
userOptions.RoIColor = [0 0 1];
userOptions.ModelColor = [0 1 0];

% Should information about the experimental design be automatically acquired from SPM metadata?
% If this option is set to true, the entries in userOptions.conditionLabels MUST correspond to the names of the conditions as specified in SPM.
%userOptions.getSPMData = false;

%%%%%%%%%%%%%%%%%%%%%%%%%%
%% ANALYSIS PREFERENCES %%
%%%%%%%%%%%%%%%%%%%%%%%%%%

%% First-order analysis

% Text lables which may be attached to the conditions for MDS plots.

% userOptions.conditionLabels = { ...
% 	'outcome_correct_LE', ...
%     'outcome_wrong_LE', ...
%     'outcome_correct_RN', ...
%     'outcome_wrong_RN', ...
% 	};
% 
% userOptions.conditionLabels = { ...
% 	'outcome_correct_LE', ...
%     'outcome_wrong_LE', ...
%     'outcome_correct_RE', ...
%     'outcome_wrong_RE', ...
% 	};
% 
% userOptions.conditionLabels = { ...
% 	'outcome_HIT_LE', ...
%     'outcome_CR_LE', ...
%     'outcome_HIT_RN', ...
%     'outcome_CR_RN', ...
% 	};
% 
% 
% userOptions.conditionLabels = { ...
% 	'outcome_HIT_LE', ...
%     'outcome_CR_LE', ...
%     'outcome_HIT_RE', ...
%     'outcome_CR_RE', ...
% 	};

[userOptions.alternativeConditionLabels{1:4}] = deal(' ');
userOptions.useAlternativeConditionLabels = true;

% What colours should be given to the conditions?
%userOptions.conditionColours = [repmat([1 0 0], 48,1); repmat([0 0 1], 44,1)];
userOptions.conditionColours = [1 0 0; 0 1 0; 0 0 1; 1 .7 0];

% Which distance measure to use when calculating first-order RDMs.
userOptions.distance = 'Correlation';

%% Second-order analysis

% Which similarity-measure is used for the second-order comparison.
userOptions.distanceMeasure = 'Spearman';

% How many permutations should be used to test the significance of the fits?  (10,000 highly recommended.)
userOptions.significanceTestPermutations = 10000;
userOptions.barsOrderedByRDMCorr = true;

% Bootstrap options
userOptions.nResamplings = 1000;
userOptions.resampleSubjects = true;
userOptions.resampleConditions = false;

% Should RDMs' entries be rank transformed into [0,1] before they're displayed?
userOptions.rankTransform = true;

% Should rubber bands be shown on the MDS plot?
userOptions.rubberbands = true;

% What criterion shoud be minimised in MDS display?
userOptions.criterion = 'metricstress';

% What is the colourscheme for the RDMs?
userOptions.colourScheme = bone(128);

% How should figures be outputted?
userOptions.displayFigures = true;
userOptions.saveFiguresPDF = true;
userOptions.saveFiguresFig = false;
userOptions.saveFiguresPS = false;
% Which dots per inch resolution do we output?
userOptions.dpi = 300;
% Remove whitespace from PDF/PS files?
% Bad if you just want to print the figures since they'll
% no longer be A4 size, good if you want to put the figure
% in a manuscript or presentation.
userOptions.tightInset = false;

userOptions.forcePromptReply = 'r';

end%function
